### ISSUE TITLE
textDocument/signatureHelp is not supported by any of the servers registered for the current buffer 

### ISSUE THREAD

**Issue by ShinyKiwis** [NvChad/NvChad#1226]
**Describe the bug**
After I installed the lsp server for css and js/ts, when finish editing a js/ts file then open the css file the error will popup whenever in "Insert Mode"

**To Reproduce**
1. Open CSS file
2. Open JS file
3. Enter the "Insert Mode" in CSS file

**Expected behavior**
The error should not appear in the bottom

**Screenshots**
![image](https://user-images.githubusercontent.com/98898032/174275687-c99ceca8-4b14-4e50-96ab-587c4af91c01.png)

**Desktop (please complete the following information):**
 - Operating System: Ubuntu
 - Terminal: Kitty
 - Version of Neovim: 0.7.0

**Additional context**
Here is my custom lspconfig.lua file: 
![image](https://user-images.githubusercontent.com/98898032/174276833-db2de3d2-1d63-4f62-af3b-68604440b343.png)
and the output of "autocmd CursorHoldI": 
![image](https://user-images.githubusercontent.com/98898032/174277063-c553ddf6-8208-4853-89d2-b654ee611d1a.png)

**Comment by siduck** [comment]
do packersync, i fixed this issue before i think

**Comment by ShinyKiwis** [comment]
I have tried packersync, but the problem is not fixed D:

**Comment by shawntarou** [comment]
I've been getting this error using css-lsp.

**Comment by siduck** [comment]
@shawntarou make sure you have latest commit of nvchad and ui

**Comment by shawntarou** [comment]
@siduck This is on a fresh install of NvChad, but it was also happening on my own config, so I'm not sure if it's a css-lsp thing, or something to do with my system. Tried uninstalling + reinstalling through Mason a couple times, still happening. This is the only thread on the internet that I could find with this message.

**Comment by siduck** [comment]
@shawntarou  can   you make a new issue on the ui repo? with a video on which syntax etc its  happening. I'll look into it tonight
